### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by ksloven** [nshalabi/ATTACK-Tools#1]
On Windows 10, I seem to be unable to open the program. I get the following Error:

`ESQLITENATIVEExpetion in AttackView.exe. [FireDac][Phys][SQLite]ERROR unable to open database file`.
The attack_view_db.sqlite is in the same folder as the AttackView.exe. Could you provide more details?
Thanks. Also, any plans on making this for *Unix systems?

**Comment by nshalabi** [comment]
The database might have a dependency that already exist on my development machine, I need to test this on another machine to determine the issue, for now, I did a slight adjustment to how I am loading the database, could you please check and let me know if it is working? Much appreciate

**Comment by PinGMUICT** [comment]
I met same issue like @ksloven on Windows 7.

![image](https://user-images.githubusercontent.com/21122064/44654918-937cc000-aa1d-11e8-8b51-083c1fb04fbf.png)

**Comment by PinGMUICT** [comment]
Great!! currently, I can execute it. 

Thanks

**Comment by nshalabi** [comment]
You welcome,
Please let me know if you face any other issues,

Regards
