### ISSUE TITLE
Delete Plans

### ISSUE THREAD

**Issue by Beercow** [nshalabi/ATTACK-Tools#2]
Is there a way to delete plans? I only see options to load and create.

**Comment by nshalabi** [comment]
The option is not there but I can add it, please note, however, that emulation plans have a one-to-many relationship with testing guidelines, meaning, one **emulation plan** "has" one or more **testing guideline**s, so deleting an emulation plan will also delete (cascade) any testing guidelines you developed as part of that emulation plan.

**Comment by nshalabi** [comment]
Added, plans can be deleted and copied.
