### ISSUE TITLE
ICS ATT&CK support

### ISSUE THREAD

**Issue by boh** [nshalabi/ATTACK-Tools#3]
I'd like to add 4th platform - **SCADA** with all the new Tactics and Techniques. (besides Windows, Linux and MacOS).

[Here](https://www.acsac.org/2017/workshops/icss/Otis-Alexander-ICS,%20Adversarial%20Tactics,%20Techniques.pdf) (_page 17_) is the ICS ATT&CK Matrix.

At the moment, it's very complicated to do so. Could you provide an information how could I edit it or if it can be incorporated into the tool?

What do you think?

**Thanks for developing this project!**

**Comment by nshalabi** [comment]
Thank you,

It is not complicated from a development perspective, I can assign an ATT&CK Technique to a new platform, I only need to change the underlying database model to create a separate table for platforms to support this model (normalize ATT&CK object further), which I already did (upcoming release), I only need to add the supporting UI.
Let me know what you think and if this is what you are looking for.

**Much appreciated your feedback**

**Comment by boh** [comment]
Awesome, this is what I was missing when interacting with ICS/SCADA environments. 
Your idea is more then sufficient.

**Comment by nshalabi** [comment]
Done, version 1.2 released:
https://twitter.com/nader_shalabi/status/1116351824217485313
