### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by joshuarivera** [nshalabi/ATTACK-Tools#7]
This database you have is EXTREMELY helpful. From my look at the bundle id's, it appears that the latest database included is version 8.1. Could you verify that this is correct? If so, do you think it would be possible to update with 9.0? 

Even better, would it be possible to get instructions on how to update the database with whatever the latest dataset is? so that it wouldn't be dependent on you updating it?

**Comment by nshalabi** [comment]
Thank you. Yes the database needs update, I am updating SysmonTools and will continue working on ATT&CK tools after.

I will also work on a utility to help import the database, it's not as straight forward as it looks, a database schema is totally not a one to one mapping with the JSON document, but will try to combine tooling with instructions.

Much appreciated

**Comment by kevinelwell** [comment]
Any updates on updating?

**Comment by nshalabi** [comment]
Updated.
Import tools and guide are in the way too.
